"""Compile the NPC spawner's behaviour scripts into spawn_script_data.h.

The scripts in src/mods/dev_overlay/scripts/*.bais are written in the AI language of the
project's level editor, whose compiler turns them into the engine's own B3D_AI record: eight
byte entries of opcode, branch and operand, and an operand pool. This tool runs that compiler
and writes the result out as C arrays, one record per script, with the slots the spawner fills
at run time listed beside each: the operands that hold a clip number, which are written with the
model's own clips, and two numbers that depend on the model, the chase speed and the reach.

Run it from the repository root whenever a .bais changes:

    python tools/compile_spawn_scripts.py --editor <path to obi-editor>

The editor is a sibling project and is not vendored here; the generated header is committed,
so building the patch never needs it. The header says which sources it came from.
"""
import argparse
import os
import struct
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SCRIPTS = os.path.join(ROOT, 'src', 'mods', 'dev_overlay', 'scripts')
OUT = os.path.join(ROOT, 'src', 'mods', 'dev_overlay', 'spawn_script_data.h')

# The records, with the four character name each script declares and whether its clips are one
# model's own (True) or placeholders the spawner fills (False). The panel's behaviours map onto
# them in spawn_scripts.c: Attack is the melee record, the shoot record or a model's own by the
# model.
RECORDS = [('stand', 'stnd', False), ('follow', 'folw', False), ('attack', 'atck', False),
           ('shoot', 'shot', False), ('droideka', 'drdk', True), ('still', 'stil', False),
           ('ally', 'ally', False), ('allyshot', 'alys', False)]

# A clip operand's role is told by the placeholder number the source uses for it.
ROLE_OF_PLACEHOLDER = {0: 'STAND', 1: 'WALK', 2: 'RUN', 11: 'ATTACK', 12: 'ATTACK2', 13: 'FIRE',
                       30: 'DEATH'}

# Which argument of which opcode is a clip number.
CLIP_ARGS = {0x201: ('anim',), 0x202: ('anim2',), 0x301: ('anim',), 0x302: ('anim',),
             0x307: ('clip',)}

# A float operand's role is told by the opcode, the argument and the value the source wrote:
# the duel Maul's 5.05 chase speed, the 3.0 walk, the 1.3 unit reach and the 6.0 unit fire
# range are the placeholders.
FLOAT_ROLES = {(0x408, 'speed', 5.05): 'CHASE_SPEED', (0x408, 'speed', 3.0): 'WALK_SPEED',
               (0x107, 'thr', 1.3): 'REACH', (0x107, 'thr', 1.4): 'ALLY_REACH',
               (0x107, 'thr', 6.0): 'FIRE_RANGE'}

# An integer operand's role, the same way: the shooter's attack kind 8, "Weapon 1", which the
# spawner keeps or turns into the twin muzzle kind for a model armed with it, and Move To's
# destination 3, the player, which a flyer trades for 0, its own record's position, kept over
# the player's head by the spawner.
INT_ROLES = {(0x307, 'kind', 8): 'SHOT_KIND', (0x201, 'tgt', 3): 'MOVE_TARGET'}

HEAD = """/* spawn_script_data.h: the NPC spawner's behaviour scripts, compiled.
 *
 * GENERATED by tools/compile_spawn_scripts.py from the .bais sources in
 * src/mods/dev_overlay/scripts, which are the files to edit. Each record is laid out
 * as the engine's B3D_AI record is: entries of (word0, word1, operand), then the
 * operand pool; the state labels are the entry index of each mode's own entry, in
 * mode order; the slots are the words the spawner fills per model, a clip number
 * for the clip roles, a float for the speeds, the reach and the fire range, and the
 * shot kind, each in the pool or, for an opcode that carries its one operand inline,
 * in the entry itself. */
#ifndef DEV_OVERLAY_SPAWN_SCRIPT_DATA_H
#define DEV_OVERLAY_SPAWN_SCRIPT_DATA_H

#include <stdint.h>

typedef enum spawn_slot_role {
    SPAWN_SLOT_STAND, SPAWN_SLOT_WALK, SPAWN_SLOT_RUN, SPAWN_SLOT_ATTACK, SPAWN_SLOT_ATTACK2,
    SPAWN_SLOT_FIRE, SPAWN_SLOT_DEATH,
    SPAWN_SLOT_CHASE_SPEED, SPAWN_SLOT_WALK_SPEED, SPAWN_SLOT_REACH, SPAWN_SLOT_ALLY_REACH,
    SPAWN_SLOT_FIRE_RANGE, SPAWN_SLOT_SHOT_KIND, SPAWN_SLOT_MOVE_TARGET
} spawn_slot_role_t;

typedef struct spawn_slot {
    uint16_t          index;      /* pool word, or entry when in_entry */
    uint8_t           in_entry;
    spawn_slot_role_t role;
} spawn_slot_t;

typedef struct spawn_script_entry {
    uint16_t word0;
    int16_t  word1;
    uint32_t operand;
} spawn_script_entry_t;

typedef struct spawn_script_record {
    const char                 *name;
    const spawn_script_entry_t *entries;
    uint32_t                    entry_count;
    const uint32_t             *pool;
    uint32_t                    pool_count;
    const uint16_t             *labels;
    uint32_t                    label_count;
    const spawn_slot_t         *slots;
    uint32_t                    slot_count;
} spawn_script_record_t;
"""


def float_bits(value):
    return struct.unpack('<I', struct.pack('<f', value))[0]


def compile_one(E, OPCODES, name, tag, fixed_clips):
    src = open(os.path.join(SCRIPTS, name + '.bais'), encoding='utf-8').read()
    rec = E.compile_source(src, script_name=tag)
    entries = rec['entries']
    pool = rec['pool']
    labels = [i for i, e in enumerate(entries) if e['op'] == 0x001]
    slots = []
    for index, e in enumerate(entries):
        op = e['op']
        inline = bool(e['word0'] & 0x4000)
        names = OPCODES[op][2] if op in OPCODES else ()
        if op in CLIP_ARGS and not inline and not fixed_clips:
            for arg in CLIP_ARGS[op]:
                k = names.index(arg)
                value = pool[e['operand'] + k]
                if value not in ROLE_OF_PLACEHOLDER:
                    raise SystemExit('%s: clip placeholder %d in %s has no role; use one of %s'
                                     % (name, value, e['op_name'], sorted(ROLE_OF_PLACEHOLDER)))
                slots.append((e['operand'] + k, 0, ROLE_OF_PLACEHOLDER[value]))
        for (fop, arg, value), role in FLOAT_ROLES.items():
            if op != fop:
                continue
            k = names.index(arg)
            if inline:
                if (e['operand'] & 0xFFFFFFFF) == float_bits(value):
                    slots.append((index, 1, role))
            elif (pool[e['operand'] + k] & 0xFFFFFFFF) == float_bits(value):
                slots.append((e['operand'] + k, 0, role))
        for (iop, arg, value), role in INT_ROLES.items():
            if op != iop or inline:
                continue
            k = names.index(arg)
            if pool[e['operand'] + k] == value:
                slots.append((e['operand'] + k, 0, role))
    return entries, pool, labels, slots


def render(name, tag, entries, pool, labels, slots):
    up = name.upper()
    out = []
    out.append('/* %s.bais, record "%s": %d entries, %d pool words, %d modes. */'
               % (name, tag, len(entries), len(pool), len(labels)))
    out.append('static const spawn_script_entry_t SPAWN_%s_ENTRIES[%d] = {' % (up, len(entries)))
    for e in entries:
        out.append('    { 0x%04X, %4d, 0x%08Xu },   /* %s */'
                   % (e['word0'], e['word1'], e['operand'] & 0xFFFFFFFF, e['op_name']))
    out.append('};')
    out.append('static const uint32_t SPAWN_%s_POOL[%d] = {' % (up, max(len(pool), 1)))
    if pool:
        for i in range(0, len(pool), 6):
            chunk = pool[i:i + 6]
            out.append('    ' + ', '.join('0x%08Xu' % (v & 0xFFFFFFFF) for v in chunk) + ',')
    else:
        out.append('    0u')
    out.append('};')
    out.append('static const uint16_t SPAWN_%s_LABELS[%d] = { %s };'
               % (up, len(labels), ', '.join(str(i) for i in labels)))
    out.append('static const spawn_slot_t SPAWN_%s_SLOTS[%d] = {' % (up, max(len(slots), 1)))
    for idx, in_entry, role in slots:
        out.append('    { %du, %du, SPAWN_SLOT_%s },' % (idx, in_entry, role))
    if not slots:
        out.append('    { 0u, 0u, SPAWN_SLOT_STAND }')
    out.append('};')
    out.append('')
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--editor', required=True, help='path to the obi-editor checkout')
    args = ap.parse_args()
    sys.path.insert(0, args.editor)
    from core.ai import emit as E                       # noqa: E402
    from core.chunks.ai import OPCODES                  # noqa: E402

    out = [HEAD]
    records = []
    for name, tag, fixed_clips in RECORDS:
        entries, pool, labels, slots = compile_one(E, OPCODES, name, tag, fixed_clips)
        out.extend(render(name, tag, entries, pool, labels, slots))
        records.append((name, tag, len(entries), len(pool), len(labels), len(slots)))

    for n, (name, tag, ne, npool, nl, nc) in enumerate(records):
        out.append('#define SPAWN_RECORD_%s %du' % (name.upper(), n))
    out.append('')
    out.append('static const spawn_script_record_t SPAWN_SCRIPTS[] = {')
    for name, tag, ne, npool, nl, nc in records:
        up = name.upper()
        out.append('    { "%s", SPAWN_%s_ENTRIES, %du, SPAWN_%s_POOL, %du,'
                   % (name, up, ne, up, npool))
        out.append('      SPAWN_%s_LABELS, %du, SPAWN_%s_SLOTS, %du },' % (up, nl, up, nc))
    out.append('};')
    out.append('#define SPAWN_SCRIPT_COUNT (sizeof SPAWN_SCRIPTS / sizeof SPAWN_SCRIPTS[0])')
    out.append('')
    out.append('#endif /* DEV_OVERLAY_SPAWN_SCRIPT_DATA_H */')
    open(OUT, 'w', encoding='utf-8', newline='\n').write('\n'.join(out) + '\n')
    for r in records:
        print('%-7s %s: %d entries, %d pool words, %d modes, %d slots' % r)
    print('wrote', os.path.relpath(OUT, ROOT))


if __name__ == '__main__':
    main()
