/* spawn_script_data.h: the NPC spawner's behaviour scripts, compiled.
 *
 * GENERATED by tools/compile_spawn_scripts.py from the .bais sources in
 * src/mods/dev_overlay/scripts, which are the files to edit. Each record is laid out
 * as the engine's B3D_AI record is: entries of (word0, word1, operand), then the
 * operand pool; the state labels are the entry index of each mode's own entry, in
 * mode order; the slots are the words the spawner fills per model, a clip number
 * for the clip roles, a float for the speeds, the reach and the fire range, and the
 * shot kind, each in the pool or, for an opcode that carries its one operand inline,
 * in the entry itself. */
#ifndef DEV_OVERLAY_SPAWN_SCRIPT_DATA_H
#define DEV_OVERLAY_SPAWN_SCRIPT_DATA_H

#include <stdint.h>

typedef enum spawn_slot_role {
    SPAWN_SLOT_STAND, SPAWN_SLOT_WALK, SPAWN_SLOT_RUN, SPAWN_SLOT_ATTACK, SPAWN_SLOT_ATTACK2,
    SPAWN_SLOT_FIRE, SPAWN_SLOT_DEATH,
    SPAWN_SLOT_CHASE_SPEED, SPAWN_SLOT_WALK_SPEED, SPAWN_SLOT_REACH, SPAWN_SLOT_ALLY_REACH,
    SPAWN_SLOT_FIRE_RANGE, SPAWN_SLOT_SHOT_KIND, SPAWN_SLOT_MOVE_TARGET
} spawn_slot_role_t;

typedef struct spawn_slot {
    uint16_t          index;      /* pool word, or entry when in_entry */
    uint8_t           in_entry;
    spawn_slot_role_t role;
} spawn_slot_t;

typedef struct spawn_script_entry {
    uint16_t word0;
    int16_t  word1;
    uint32_t operand;
} spawn_script_entry_t;

typedef struct spawn_script_record {
    const char                 *name;
    const spawn_script_entry_t *entries;
    uint32_t                    entry_count;
    const uint32_t             *pool;
    uint32_t                    pool_count;
    const uint16_t             *labels;
    uint32_t                    label_count;
    const spawn_slot_t         *slots;
    uint32_t                    slot_count;
} spawn_script_record_t;

/* stand.bais, record "stnd": 21 entries, 8 pool words, 3 modes. */
static const spawn_script_entry_t SPAWN_STAND_ENTRIES[21] = {
    { 0x0000,    1, 0x646E7473u },   /* AI Name */
    { 0x4102,    3, 0x00000000u },   /* Check Death? */
    { 0x4400,    1, 0x00000001u },   /* Set AI Mode */
    { 0x4106,   -1, 0x00000000u },   /* Mode Jmp */
    { 0x4106,    1, 0x00000000u },   /* Mode Jmp */
    { 0x0001,    5, 0x656C6469u },   /* AI Mode */
    { 0x4408,    1, 0x00000000u },   /* Move Speed */
    { 0x0201,    2, 0x00000000u },   /* Move To */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x0001,    6, 0x00656964u },   /* AI Mode */
    { 0x0202,    4, 0x00000003u },   /* Animation */
    { 0x440F,    1, 0x00000000u },   /* Start Timer */
    { 0x4400,    1, 0x00000002u },   /* Set AI Mode */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x0001,   -1, 0x656E6F67u },   /* AI Mode */
    { 0x0109,    3, 0x00000006u },   /* Check Timer? */
    { 0x420B,    1, 0x00000000u },   /* AI Killed */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
};
static const uint32_t SPAWN_STAND_POOL[8] = {
    0x00000003u, 0x00000000u, 0x3F000000u, 0x00000000u, 0x0000001Eu, 0x00000000u,
    0x00000001u, 0x41000000u,
};
static const uint16_t SPAWN_STAND_LABELS[3] = { 5, 10, 16 };
static const spawn_slot_t SPAWN_STAND_SLOTS[3] = {
    { 1u, 0u, SPAWN_SLOT_STAND },
    { 0u, 0u, SPAWN_SLOT_MOVE_TARGET },
    { 4u, 0u, SPAWN_SLOT_DEATH },
};

/* follow.bais, record "folw": 32 entries, 17 pool words, 4 modes. */
static const spawn_script_entry_t SPAWN_FOLLOW_ENTRIES[32] = {
    { 0x0000,    1, 0x776C6F66u },   /* AI Name */
    { 0x4102,    3, 0x00000000u },   /* Check Death? */
    { 0x4400,    1, 0x00000001u },   /* Set AI Mode */
    { 0x4106,   -1, 0x00000000u },   /* Mode Jmp */
    { 0x4106,    1, 0x00000000u },   /* Mode Jmp */
    { 0x0001,    8, 0x776C6F66u },   /* AI Mode */
    { 0x0107,    3, 0x00000000u },   /* Range Check? */
    { 0x4400,    1, 0x00000003u },   /* Set AI Mode */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4408,    1, 0x40400000u },   /* Move Speed */
    { 0x0201,    2, 0x00000003u },   /* Move To */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x0001,    6, 0x00656964u },   /* AI Mode */
    { 0x0202,    4, 0x00000006u },   /* Animation */
    { 0x440F,    1, 0x00000000u },   /* Start Timer */
    { 0x4400,    1, 0x00000002u },   /* Set AI Mode */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x0001,    5, 0x656E6F67u },   /* AI Mode */
    { 0x0109,    3, 0x00000009u },   /* Check Timer? */
    { 0x420B,    1, 0x00000000u },   /* AI Killed */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x0001,   -1, 0x7261656Eu },   /* AI Mode */
    { 0x0107,    5, 0x0000000Bu },   /* Range Check? */
    { 0x4408,    1, 0x00000000u },   /* Move Speed */
    { 0x0201,    2, 0x0000000Eu },   /* Move To */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4400,    1, 0x00000000u },   /* Set AI Mode */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
};
static const uint32_t SPAWN_FOLLOW_POOL[17] = {
    0x00000000u, 0x00000002u, 0x3FC00000u, 0x00000003u, 0x00000001u, 0x3FC00000u,
    0x00000000u, 0x0000001Eu, 0x00000000u, 0x00000001u, 0x41000000u, 0x00000000u,
    0x00000002u, 0x40400000u, 0x00000003u, 0x00000000u, 0x3F000000u,
};
static const uint16_t SPAWN_FOLLOW_LABELS[4] = { 5, 13, 19, 24 };
static const spawn_slot_t SPAWN_FOLLOW_SLOTS[6] = {
    { 9u, 1u, SPAWN_SLOT_WALK_SPEED },
    { 4u, 0u, SPAWN_SLOT_WALK },
    { 3u, 0u, SPAWN_SLOT_MOVE_TARGET },
    { 7u, 0u, SPAWN_SLOT_DEATH },
    { 15u, 0u, SPAWN_SLOT_STAND },
    { 14u, 0u, SPAWN_SLOT_MOVE_TARGET },
};

/* attack.bais, record "atck": 37 entries, 24 pool words, 5 modes. */
static const spawn_script_entry_t SPAWN_ATTACK_ENTRIES[37] = {
    { 0x0000,    1, 0x6B637461u },   /* AI Name */
    { 0x4102,    3, 0x00000000u },   /* Check Death? */
    { 0x4400,    1, 0x00000003u },   /* Set AI Mode */
    { 0x4106,   -1, 0x00000000u },   /* Mode Jmp */
    { 0x4106,    1, 0x00000000u },   /* Mode Jmp */
    { 0x0001,    8, 0x746E7568u },   /* AI Mode */
    { 0x0107,    3, 0x00000000u },   /* Range Check? */
    { 0x4400,    1, 0x00000001u },   /* Set AI Mode */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4408,    1, 0x40A1999Au },   /* Move Speed */
    { 0x0201,    2, 0x00000003u },   /* Move To */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x0001,    8, 0x676E7773u },   /* AI Mode */
    { 0x0301,    6, 0x00000006u },   /* Slash */
    { 0x0107,    3, 0x0000000Bu },   /* Range Check? */
    { 0x4400,    1, 0x00000002u },   /* Set AI Mode */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4400,    1, 0x00000000u },   /* Set AI Mode */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x0001,    5, 0x6E696761u },   /* AI Mode */
    { 0x0301,    3, 0x0000000Eu },   /* Slash */
    { 0x4400,    1, 0x00000000u },   /* Set AI Mode */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x0001,    6, 0x00656964u },   /* AI Mode */
    { 0x0202,    4, 0x00000013u },   /* Animation */
    { 0x440F,    1, 0x00000000u },   /* Start Timer */
    { 0x4400,    1, 0x00000004u },   /* Set AI Mode */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x0001,   -1, 0x656E6F67u },   /* AI Mode */
    { 0x0109,    3, 0x00000016u },   /* Check Timer? */
    { 0x420B,    1, 0x00000000u },   /* AI Killed */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
};
static const uint32_t SPAWN_ATTACK_POOL[24] = {
    0x00000000u, 0x00000002u, 0x3FA66666u, 0x00000003u, 0x00000002u, 0x3F19999Au,
    0x00000000u, 0x0000000Bu, 0x00000005u, 0x00000000u, 0x00000000u, 0x00000000u,
    0x00000002u, 0x3FA66666u, 0x00000000u, 0x0000000Cu, 0x0000000Du, 0x00000000u,
    0x00000000u, 0x00000000u, 0x0000001Eu, 0x00000000u, 0x00000001u, 0x41000000u,
};
static const uint16_t SPAWN_ATTACK_LABELS[5] = { 5, 13, 21, 26, 32 };
static const spawn_slot_t SPAWN_ATTACK_SLOTS[8] = {
    { 2u, 0u, SPAWN_SLOT_REACH },
    { 9u, 1u, SPAWN_SLOT_CHASE_SPEED },
    { 4u, 0u, SPAWN_SLOT_RUN },
    { 3u, 0u, SPAWN_SLOT_MOVE_TARGET },
    { 7u, 0u, SPAWN_SLOT_ATTACK },
    { 13u, 0u, SPAWN_SLOT_REACH },
    { 15u, 0u, SPAWN_SLOT_ATTACK2 },
    { 20u, 0u, SPAWN_SLOT_DEATH },
};

/* shoot.bais, record "shot": 25 entries, 15 pool words, 3 modes. */
static const spawn_script_entry_t SPAWN_SHOOT_ENTRIES[25] = {
    { 0x0000,    1, 0x746F6873u },   /* AI Name */
    { 0x4102,    3, 0x00000000u },   /* Check Death? */
    { 0x4400,    1, 0x00000001u },   /* Set AI Mode */
    { 0x4106,   -1, 0x00000000u },   /* Mode Jmp */
    { 0x4106,    1, 0x00000000u },   /* Mode Jmp */
    { 0x0001,    9, 0x746F6873u },   /* AI Mode */
    { 0x0107,    4, 0x00000000u },   /* Range Check? */
    { 0x4408,    1, 0x00000000u },   /* Move Speed */
    { 0x0307,    1, 0x00000003u },   /* ShootEmUp */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4408,    1, 0x40400000u },   /* Move Speed */
    { 0x0201,    2, 0x00000007u },   /* Move To */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x0001,    6, 0x00656964u },   /* AI Mode */
    { 0x0202,    4, 0x0000000Au },   /* Animation */
    { 0x440F,    1, 0x00000000u },   /* Start Timer */
    { 0x4400,    1, 0x00000002u },   /* Set AI Mode */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x0001,   -1, 0x656E6F67u },   /* AI Mode */
    { 0x0109,    3, 0x0000000Du },   /* Check Timer? */
    { 0x420B,    1, 0x00000000u },   /* AI Killed */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
};
static const uint32_t SPAWN_SHOOT_POOL[15] = {
    0x00000000u, 0x00000002u, 0x40C00000u, 0x00000008u, 0x00000000u, 0x00000000u,
    0x0000000Du, 0x00000003u, 0x00000001u, 0x40A00000u, 0x00000000u, 0x0000001Eu,
    0x00000000u, 0x00000001u, 0x41000000u,
};
static const uint16_t SPAWN_SHOOT_LABELS[3] = { 5, 14, 20 };
static const spawn_slot_t SPAWN_SHOOT_SLOTS[7] = {
    { 2u, 0u, SPAWN_SLOT_FIRE_RANGE },
    { 6u, 0u, SPAWN_SLOT_FIRE },
    { 3u, 0u, SPAWN_SLOT_SHOT_KIND },
    { 10u, 1u, SPAWN_SLOT_WALK_SPEED },
    { 8u, 0u, SPAWN_SLOT_WALK },
    { 7u, 0u, SPAWN_SLOT_MOVE_TARGET },
    { 11u, 0u, SPAWN_SLOT_DEATH },
};

/* droideka.bais, record "drdk": 62 entries, 53 pool words, 6 modes. */
static const spawn_script_entry_t SPAWN_DROIDEKA_ENTRIES[62] = {
    { 0x0000,    1, 0x6B647264u },   /* AI Name */
    { 0x4102,    3, 0x00000000u },   /* Check Death? */
    { 0x4400,    1, 0x00000004u },   /* Set AI Mode */
    { 0x4106,   -1, 0x00000000u },   /* Mode Jmp */
    { 0x4103,   10, 0x00000000u },   /* Chk For Hit? */
    { 0x0101,    8, 0x00000000u },   /* Chk Count? */
    { 0x040C,    1, 0x00000003u },   /* Set Hit Pnts */
    { 0x010A,    5, 0x00000005u },   /* Hit Points? */
    { 0x0405,    1, 0x00000007u },   /* Set Count */
    { 0x0606,    2, 0x00000009u },   /* Extra Func */
    { 0x4106,   -1, 0x00000000u },   /* Mode Jmp */
    { 0x4106,   -1, 0x00000000u },   /* Mode Jmp */
    { 0x4106,   -1, 0x00000000u },   /* Mode Jmp */
    { 0x4106,   -1, 0x00000000u },   /* Mode Jmp */
    { 0x4106,    1, 0x00000000u },   /* Mode Jmp */
    { 0x0001,    9, 0x6C6C6F72u },   /* AI Mode */
    { 0x0107,    4, 0x0000000Cu },   /* Range Check? */
    { 0x4408,    1, 0x00000000u },   /* Move Speed */
    { 0x4400,    1, 0x00000001u },   /* Set AI Mode */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4408,    1, 0x40600000u },   /* Move Speed */
    { 0x0201,    2, 0x0000000Fu },   /* Move To */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x0001,   10, 0x6F666E75u },   /* AI Mode */
    { 0x0202,    8, 0x00000012u },   /* Animation */
    { 0x0411,    1, 0x00000015u },   /* Set Cylinder */
    { 0x0405,    1, 0x00000017u },   /* Set Count */
    { 0x0606,    3, 0x00000019u },   /* Extra Func */
    { 0x4400,    1, 0x00000002u },   /* Set AI Mode */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4400,    1, 0x00000002u },   /* Set AI Mode */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x0001,    6, 0x65726966u },   /* AI Mode */
    { 0x0107,    3, 0x0000001Cu },   /* Range Check? */
    { 0x0307,    1, 0x0000001Fu },   /* ShootEmUp */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4400,    1, 0x00000003u },   /* Set AI Mode */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x0001,    9, 0x646C6F66u },   /* AI Mode */
    { 0x0405,    1, 0x00000023u },   /* Set Count */
    { 0x0606,    2, 0x00000025u },   /* Extra Func */
    { 0x4108,    1, 0x00000000u },   /* Continue */
    { 0x0202,    4, 0x00000028u },   /* Animation */
    { 0x0411,    1, 0x0000002Bu },   /* Set Cylinder */
    { 0x4400,    1, 0x00000000u },   /* Set AI Mode */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x0001,    8, 0x00656964u },   /* AI Mode */
    { 0x0606,    2, 0x0000002Du },   /* Extra Func */
    { 0x4108,    1, 0x00000000u },   /* Continue */
    { 0x0202,    4, 0x00000030u },   /* Animation */
    { 0x440F,    1, 0x00000000u },   /* Start Timer */
    { 0x4400,    1, 0x00000005u },   /* Set AI Mode */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x0001,   -1, 0x656E6F67u },   /* AI Mode */
    { 0x0109,    3, 0x00000033u },   /* Check Timer? */
    { 0x420B,    1, 0x00000000u },   /* AI Killed */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
};
static const uint32_t SPAWN_DROIDEKA_POOL[53] = {
    0x00000004u, 0x00000000u, 0x00000000u, 0x00000001u, 0x00000003u, 0x00000002u,
    0x00000019u, 0x00000004u, 0x00000001u, 0x00000004u, 0x00000000u, 0x00000000u,
    0x00000000u, 0x00000002u, 0x40200000u, 0x00000003u, 0x00000002u, 0x3F000000u,
    0x00000000u, 0x00000003u, 0x00000000u, 0x3ECCCCCDu, 0x3F4CCCCDu, 0x00000004u,
    0x00000000u, 0x00000002u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000002u,
    0x40E00000u, 0x00000002u, 0x00000000u, 0x00000000u, 0x00000001u, 0x00000004u,
    0x00000001u, 0x00000003u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000005u,
    0x00000000u, 0x3E800000u, 0x3F4CCCCDu, 0x00000003u, 0x00000000u, 0x00000000u,
    0x00000000u, 0x00000006u, 0x00000000u, 0x00000001u, 0x41000000u,
};
static const uint16_t SPAWN_DROIDEKA_LABELS[6] = { 15, 24, 34, 40, 49, 57 };
static const spawn_slot_t SPAWN_DROIDEKA_SLOTS[1] = {
    { 15u, 0u, SPAWN_SLOT_MOVE_TARGET },
};

/* still.bais, record "stil": 18 entries, 5 pool words, 3 modes. */
static const spawn_script_entry_t SPAWN_STILL_ENTRIES[18] = {
    { 0x0000,    1, 0x6C697473u },   /* AI Name */
    { 0x4102,    3, 0x00000000u },   /* Check Death? */
    { 0x4400,    1, 0x00000001u },   /* Set AI Mode */
    { 0x4106,   -1, 0x00000000u },   /* Mode Jmp */
    { 0x4106,    1, 0x00000000u },   /* Mode Jmp */
    { 0x0001,    2, 0x6C697473u },   /* AI Mode */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x0001,    6, 0x00656964u },   /* AI Mode */
    { 0x0202,    4, 0x00000000u },   /* Animation */
    { 0x440F,    1, 0x00000000u },   /* Start Timer */
    { 0x4400,    1, 0x00000002u },   /* Set AI Mode */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x0001,   -1, 0x656E6F67u },   /* AI Mode */
    { 0x0109,    3, 0x00000003u },   /* Check Timer? */
    { 0x420B,    1, 0x00000000u },   /* AI Killed */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
};
static const uint32_t SPAWN_STILL_POOL[5] = {
    0x00000000u, 0x0000001Eu, 0x00000000u, 0x00000001u, 0x41000000u,
};
static const uint16_t SPAWN_STILL_LABELS[3] = { 5, 7, 13 };
static const spawn_slot_t SPAWN_STILL_SLOTS[1] = {
    { 1u, 0u, SPAWN_SLOT_DEATH },
};

/* ally.bais, record "ally": 62 entries, 45 pool words, 7 modes. */
static const spawn_script_entry_t SPAWN_ALLY_ENTRIES[62] = {
    { 0x0000,    1, 0x796C6C61u },   /* AI Name */
    { 0x4102,    3, 0x00000000u },   /* Check Death? */
    { 0x4400,    1, 0x00000004u },   /* Set AI Mode */
    { 0x4106,   -1, 0x00000000u },   /* Mode Jmp */
    { 0x4106,    1, 0x00000000u },   /* Mode Jmp */
    { 0x0001,   11, 0x776C6F66u },   /* AI Mode */
    { 0x0107,    3, 0x00000000u },   /* Range Check? */
    { 0x4400,    1, 0x00000001u },   /* Set AI Mode */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x0107,    3, 0x00000003u },   /* Range Check? */
    { 0x4400,    1, 0x00000006u },   /* Set AI Mode */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4408,    1, 0x40400000u },   /* Move Speed */
    { 0x0201,    2, 0x00000006u },   /* Move To */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x0001,   11, 0x746E7568u },   /* AI Mode */
    { 0x0107,    3, 0x00000009u },   /* Range Check? */
    { 0x4400,    1, 0x00000002u },   /* Set AI Mode */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x0107,    5, 0x0000000Cu },   /* Range Check? */
    { 0x4408,    1, 0x40A1999Au },   /* Move Speed */
    { 0x0201,    2, 0x0000000Fu },   /* Move To */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4400,    1, 0x00000000u },   /* Set AI Mode */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x0001,    8, 0x676E7773u },   /* AI Mode */
    { 0x0301,    6, 0x00000012u },   /* Slash */
    { 0x0107,    3, 0x00000017u },   /* Range Check? */
    { 0x4400,    1, 0x00000003u },   /* Set AI Mode */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4400,    1, 0x00000001u },   /* Set AI Mode */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x0001,    5, 0x6E696761u },   /* AI Mode */
    { 0x0301,    3, 0x0000001Au },   /* Slash */
    { 0x4400,    1, 0x00000001u },   /* Set AI Mode */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x0001,    6, 0x00656964u },   /* AI Mode */
    { 0x0202,    4, 0x0000001Fu },   /* Animation */
    { 0x440F,    1, 0x00000000u },   /* Start Timer */
    { 0x4400,    1, 0x00000005u },   /* Set AI Mode */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x0001,    5, 0x656E6F67u },   /* AI Mode */
    { 0x0109,    3, 0x00000022u },   /* Check Timer? */
    { 0x420B,    1, 0x00000000u },   /* AI Killed */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x0001,   -1, 0x7261656Eu },   /* AI Mode */
    { 0x0107,    3, 0x00000024u },   /* Range Check? */
    { 0x4400,    1, 0x00000001u },   /* Set AI Mode */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x0107,    5, 0x00000027u },   /* Range Check? */
    { 0x4408,    1, 0x00000000u },   /* Move Speed */
    { 0x0201,    2, 0x0000002Au },   /* Move To */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4400,    1, 0x00000000u },   /* Set AI Mode */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
};
static const uint32_t SPAWN_ALLY_POOL[45] = {
    0x00000002u, 0x00000002u, 0x41200000u, 0x00000000u, 0x00000002u, 0x3FC00000u,
    0x00000003u, 0x00000001u, 0x3FC00000u, 0x00000002u, 0x00000002u, 0x3FB33333u,
    0x00000002u, 0x00000002u, 0x41200000u, 0x00000004u, 0x00000002u, 0x3DCCCCCDu,
    0x00000002u, 0x0000000Bu, 0x00000005u, 0x00000001u, 0x00000000u, 0x00000002u,
    0x00000002u, 0x3FB33333u, 0x00000002u, 0x0000000Cu, 0x0000000Du, 0x00000001u,
    0x00000000u, 0x00000000u, 0x0000001Eu, 0x00000000u, 0x00000001u, 0x41000000u,
    0x00000002u, 0x00000002u, 0x41200000u, 0x00000000u, 0x00000002u, 0x40400000u,
    0x00000003u, 0x00000000u, 0x3F000000u,
};
static const uint16_t SPAWN_ALLY_LABELS[7] = { 5, 16, 27, 35, 40, 46, 51 };
static const spawn_slot_t SPAWN_ALLY_SLOTS[12] = {
    { 12u, 1u, SPAWN_SLOT_WALK_SPEED },
    { 7u, 0u, SPAWN_SLOT_WALK },
    { 6u, 0u, SPAWN_SLOT_MOVE_TARGET },
    { 11u, 0u, SPAWN_SLOT_ALLY_REACH },
    { 21u, 1u, SPAWN_SLOT_CHASE_SPEED },
    { 16u, 0u, SPAWN_SLOT_RUN },
    { 19u, 0u, SPAWN_SLOT_ATTACK },
    { 25u, 0u, SPAWN_SLOT_ALLY_REACH },
    { 27u, 0u, SPAWN_SLOT_ATTACK2 },
    { 32u, 0u, SPAWN_SLOT_DEATH },
    { 43u, 0u, SPAWN_SLOT_STAND },
    { 42u, 0u, SPAWN_SLOT_MOVE_TARGET },
};

/* allyshot.bais, record "alys": 39 entries, 27 pool words, 4 modes. */
static const spawn_script_entry_t SPAWN_ALLYSHOT_ENTRIES[39] = {
    { 0x0000,    1, 0x73796C61u },   /* AI Name */
    { 0x4102,    3, 0x00000000u },   /* Check Death? */
    { 0x4400,    1, 0x00000001u },   /* Set AI Mode */
    { 0x4106,   -1, 0x00000000u },   /* Mode Jmp */
    { 0x4106,    1, 0x00000000u },   /* Mode Jmp */
    { 0x0001,   12, 0x776C6F66u },   /* AI Mode */
    { 0x0107,    4, 0x00000000u },   /* Range Check? */
    { 0x4408,    1, 0x00000000u },   /* Move Speed */
    { 0x0307,    1, 0x00000003u },   /* ShootEmUp */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x0107,    3, 0x00000007u },   /* Range Check? */
    { 0x4400,    1, 0x00000003u },   /* Set AI Mode */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4408,    1, 0x40400000u },   /* Move Speed */
    { 0x0201,    2, 0x0000000Au },   /* Move To */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x0001,    6, 0x00656964u },   /* AI Mode */
    { 0x0202,    4, 0x0000000Du },   /* Animation */
    { 0x440F,    1, 0x00000000u },   /* Start Timer */
    { 0x4400,    1, 0x00000002u },   /* Set AI Mode */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x0001,    5, 0x656E6F67u },   /* AI Mode */
    { 0x0109,    3, 0x00000010u },   /* Check Timer? */
    { 0x420B,    1, 0x00000000u },   /* AI Killed */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x0001,   -1, 0x7261656Eu },   /* AI Mode */
    { 0x0107,    3, 0x00000012u },   /* Range Check? */
    { 0x4400,    1, 0x00000000u },   /* Set AI Mode */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x0107,    5, 0x00000015u },   /* Range Check? */
    { 0x4408,    1, 0x00000000u },   /* Move Speed */
    { 0x0201,    2, 0x00000018u },   /* Move To */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
    { 0x4400,    1, 0x00000000u },   /* Set AI Mode */
    { 0x4200,   -1, 0x00000000u },   /* End Cycle */
};
static const uint32_t SPAWN_ALLYSHOT_POOL[27] = {
    0x00000002u, 0x00000002u, 0x41400000u, 0x00000008u, 0x00000000u, 0x00000002u,
    0x0000000Du, 0x00000000u, 0x00000002u, 0x3FC00000u, 0x00000003u, 0x00000001u,
    0x3FC00000u, 0x00000000u, 0x0000001Eu, 0x00000000u, 0x00000001u, 0x41000000u,
    0x00000002u, 0x00000002u, 0x41400000u, 0x00000000u, 0x00000002u, 0x40400000u,
    0x00000003u, 0x00000000u, 0x3F000000u,
};
static const uint16_t SPAWN_ALLYSHOT_LABELS[4] = { 5, 17, 23, 28 };
static const spawn_slot_t SPAWN_ALLYSHOT_SLOTS[8] = {
    { 6u, 0u, SPAWN_SLOT_FIRE },
    { 3u, 0u, SPAWN_SLOT_SHOT_KIND },
    { 13u, 1u, SPAWN_SLOT_WALK_SPEED },
    { 11u, 0u, SPAWN_SLOT_WALK },
    { 10u, 0u, SPAWN_SLOT_MOVE_TARGET },
    { 14u, 0u, SPAWN_SLOT_DEATH },
    { 25u, 0u, SPAWN_SLOT_STAND },
    { 24u, 0u, SPAWN_SLOT_MOVE_TARGET },
};

#define SPAWN_RECORD_STAND 0u
#define SPAWN_RECORD_FOLLOW 1u
#define SPAWN_RECORD_ATTACK 2u
#define SPAWN_RECORD_SHOOT 3u
#define SPAWN_RECORD_DROIDEKA 4u
#define SPAWN_RECORD_STILL 5u
#define SPAWN_RECORD_ALLY 6u
#define SPAWN_RECORD_ALLYSHOT 7u

static const spawn_script_record_t SPAWN_SCRIPTS[] = {
    { "stand", SPAWN_STAND_ENTRIES, 21u, SPAWN_STAND_POOL, 8u,
      SPAWN_STAND_LABELS, 3u, SPAWN_STAND_SLOTS, 3u },
    { "follow", SPAWN_FOLLOW_ENTRIES, 32u, SPAWN_FOLLOW_POOL, 17u,
      SPAWN_FOLLOW_LABELS, 4u, SPAWN_FOLLOW_SLOTS, 6u },
    { "attack", SPAWN_ATTACK_ENTRIES, 37u, SPAWN_ATTACK_POOL, 24u,
      SPAWN_ATTACK_LABELS, 5u, SPAWN_ATTACK_SLOTS, 8u },
    { "shoot", SPAWN_SHOOT_ENTRIES, 25u, SPAWN_SHOOT_POOL, 15u,
      SPAWN_SHOOT_LABELS, 3u, SPAWN_SHOOT_SLOTS, 7u },
    { "droideka", SPAWN_DROIDEKA_ENTRIES, 62u, SPAWN_DROIDEKA_POOL, 53u,
      SPAWN_DROIDEKA_LABELS, 6u, SPAWN_DROIDEKA_SLOTS, 1u },
    { "still", SPAWN_STILL_ENTRIES, 18u, SPAWN_STILL_POOL, 5u,
      SPAWN_STILL_LABELS, 3u, SPAWN_STILL_SLOTS, 1u },
    { "ally", SPAWN_ALLY_ENTRIES, 62u, SPAWN_ALLY_POOL, 45u,
      SPAWN_ALLY_LABELS, 7u, SPAWN_ALLY_SLOTS, 12u },
    { "allyshot", SPAWN_ALLYSHOT_ENTRIES, 39u, SPAWN_ALLYSHOT_POOL, 27u,
      SPAWN_ALLYSHOT_LABELS, 4u, SPAWN_ALLYSHOT_SLOTS, 8u },
};
#define SPAWN_SCRIPT_COUNT (sizeof SPAWN_SCRIPTS / sizeof SPAWN_SCRIPTS[0])

#endif /* DEV_OVERLAY_SPAWN_SCRIPT_DATA_H */
